### ISSUE TITLE
Error accessing cloud connector https://localhost:8443 

### ISSUE THREAD

**Issue by jhonj98** [SAP-samples/cloud-platform-workflow-virtual-event#1]
Hello Devtoberfest team,

It seems I'm the first reporting an issue or this is not the place to do it, even it could be that nobody have had issues yet haha....

So, the fact is that I was doing the docker image process (build) when I face the following messages in the tracing log:

![image](https://user-images.githubusercontent.com/10300948/91326359-db0fc100-e789-11ea-850f-e5999854a958.png)

![image](https://user-images.githubusercontent.com/10300948/91326378-e19e3880-e789-11ea-8493-27621b140fa3.png)

When I run the image no errors are issued but when I try to access the https://localhost:8443 is displaying the following error:

![image](https://user-images.githubusercontent.com/10300948/91326573-1a3e1200-e78a-11ea-99ee-b3e38de18669.png)

This was made using windows 10 Professional as the base operating system.

Please your kind help.

Jhon Jairo.

**Comment by jhonj98** [comment]
By the way if I do docker ps it seems everything is ok

![image](https://user-images.githubusercontent.com/10300948/91327010-a0f2ef00-e78a-11ea-9370-3854ddf2e52f.png)

Thanks.

**Comment by SandorAguilar** [comment]
Same thing happened to me with Chrome. I was able to access the site on Internet Explorer by clicking on "Go on to the webpage (not recommended)" link. By default, IE will note that the site is not secured.

**Comment by jhonj98** [comment]
Thank you Sandor, I tested in IE and it works, thank you very much.
